### ISSUE TITLE
onAfterDeployExecute never executing commands

### ISSUE THREAD

**Issue by akelley** [la-haute-societe/grunt-ssh-deploy-release#1]
I have the following configuration:

```
'ssh-deploy-release': {
			options:{
				localPath: '.',
				exclude: ['.project','.git/**','.gitignore','.settings/**','.jshintrc','.tern-project','.bowerrc'],
				currentReleaseLink: 'current',
			},
		    dev: {
		        options: {
		            host: 'myHost.com',
		            username: 'nodejs',
		            password: '*********',
		            deployPath: '/software/app/node/app',
		            onAfterDeployExecute:[''cd /software/app/node/app/current',
				                                 'forever start -a --uid myApp bin/www']
		        }
		    },
```
The application deploys fine but the onAfterDeployExecute commands seem to never be executed, no errors are thrown or no notification on what it is doing are shown, but the application is never started with forever.

**Comment by maxime-colin** [comment]
Each command of the `onAfterDeployExecute` array is executed in a different "thread". 
Maybe you could try this : 
```
...
onAfterDeployExecute: [
     'cd /software/app/node/app/current && forever start -a --uid myApp bin/www'
]
...
```

You can enable grunt debug with `--debug` option : 
```
grunt ssh-deploy-release:dev --debug
```

**Comment by akelley** [comment]
Thanks turning on debug helps in seeing what it is actually doing, but my issue still persists.  I even changed the command to the following:
`     onAfterDeployExecute:['forever stop myApp']`
(It is currently running before the deployment.)  During the run -

Update current release symlink on remote
```
[D] Remote command : mkdir -p `dirname /software/app/node/myApp/current` && rm -rf /software/app/node/myApp/current && mkdir -p /software/app/node/myApp/releases/2017-01-24-19-01-22-433-UTC && cd /software/app/node/myApp/releases/2017-01-24-19-01-22-433-UTC && ln -nfs releases/2017-01-24-19-01-22-433-UT
C /software/app/node/myApp/current
>> Done
>> Done
[D] Remote command : forever stop myApp
>> Done

```
But logging into the remote system  and running a forever list shows the process still running...

**Comment by maxime-colin** [comment]
Upgrade to 1.7.0 and try the following configuration : 

```
...
onAfterDeployExecute: [
     'pwd'
]
...
```

It should display the current path where command is executed. Maybe you need to "cd" to the right folder before executing "forever" ?

**Comment by akelley** [comment]
Thanks I see the issue now - I had configured my environment variables for node in the users ~/.bash_profile:

`PATH=$PATH:$HOME/.local/bin:$HOME/bin:/software/nodejs/bin`

I guess during the SSH connection the profile was not being sourced so adding the following before any node or forever commands has it working -

`onAfterDeployExecute:['source ~/.bash_profile && forever list']`

Is this normal and expected behavior?

**Comment by maxime-colin** [comment]
Thanks, good to know ! I think it's related to this issue on the ssh2 package : https://github.com/mscdex/ssh2/issues/77

I had the same issue, and proceed like this : 
```
onAfterDeployExecute:['set -i && source ~/.bashrc && my command']
```
