### ISSUE TITLE
Possible to save compressed file locally during deployment?

### ISSUE THREAD

**Issue by akelley** [la-haute-societe/grunt-ssh-deploy-release#2]
I read through the options and documentation but could not seem to see if this was possible already.  I want to be able to keep the local compressed archive.  Not sure if I am missing this configuration or if it does not yet exist.

**Comment by maxime-colin** [comment]
I added `deleteLocalArchiveAfterDeployment` option : https://github.com/la-haute-societe/grunt-ssh-deploy-release#deletelocalarchiveafterdeployment

You have to upgrade to the version 1.11.0 and set this option to `false` in order to keep the local release.
