### ISSUE TITLE
/www not symlinked to releases/folder

### ISSUE THREAD

**Issue by justusdeitert** [la-haute-societe/grunt-ssh-deploy-release#6]
Hey there! Your Grunt Plugin looks really good so far! It Just doesnt work for me: The /www Folder is not symlinked to the current releases Folder, instead the Folder Structure looks like in the Picture below. Am I doing Something wrong? Cheers, Justus
![symlink_not_working](https://user-images.githubusercontent.com/6768651/27141109-a73f8122-5127-11e7-8601-6eb847e91692.png)

**Comment by nstcactus** [comment]
Could you please post you gruntfile?

**Comment by justusdeitert** [comment]
For Sure! The grunt-ssh-deploy-release Task is located at the bottom. I used grunt-ssh-deploy before, but its old and not that flexible..
[Gruntfile.js.zip](https://github.com/la-haute-societe/grunt-ssh-deploy-release/files/1075182/Gruntfile.js.zip)

**Comment by maxime-colin** [comment]
I have tested with a simplified version of your Gruntfile, here is what I have obtained with this command :

```
grunt ssh-deploy-release:production
```

Example : 
[deploy.zip](https://github.com/la-haute-societe/grunt-ssh-deploy-release/files/1075618/deploy.zip)

Results :
![image](https://user-images.githubusercontent.com/4800745/27149743-e6c08c34-5144-11e7-8d9c-7b81f07f88f1.png)

Keep me in touch

**Comment by justusdeitert** [comment]
mhh.. still got the same problem. i tryed it with your simplified version. thx for that btw.
![screen shot 2017-06-15 at 07 59 09](https://user-images.githubusercontent.com/6768651/27167414-f972e0dc-51a0-11e7-955a-200ec9e7399f.png)

if i run grunt ssh-deploy-release:production with debug it prints out the following commands.
![screen shot 2017-06-15 at 08 05 10](https://user-images.githubusercontent.com/6768651/27167516-796a299e-51a1-11e7-9ea6-ab4402dfb169.png)

the server runs on Ubuntu 14.04.5 LTS‬

**Comment by maxime-colin** [comment]
I found what was wrong, the path to the release wasn't right when `deployPath` is a root folder.

I released a fix (version 2.0.10 - https://github.com/la-haute-societe/ssh-deploy-release/commit/52de8e0e697ddab11003880220b2a5dcc3b88b41)


![image](https://user-images.githubusercontent.com/4800745/27176496-021f6cc4-51c3-11e7-9b1f-f5ee8a405b7b.png)

**Comment by justusdeitert** [comment]
Hey! It works like a charm now!! Thanx for your fast reply and fix! Great work. I really appreciate.
Don't forget to update the grunt-ssh-deploy-release package.json aswell! https://github.com/la-haute-societe/grunt-ssh-deploy-release cheers guys!!
