### ISSUE TITLE
Fatal error : Error: Handshake failed: no matching key exchange algorithm

### ISSUE THREAD

**Issue by justusdeitert** [la-haute-societe/grunt-ssh-deploy-release#7]
On One of my Servers I got this Problem. What could it be? Should i set up a privateKeyFile ? Cheers, Justus

**Comment by maxime-colin** [comment]
It seems it's an issue with the ssh2 package. The options object is forwarded to ssh2 methods, which means you can set all ssh2 options (see https://github.com/la-haute-societe/ssh-deploy-release#options).

Maybe this can help you : https://github.com/mscdex/ssh2/issues/536

**Comment by justusdeitert** [comment]
hey! thanks for your help maxime! that was the problem. i just added all the supported algorithms (more then the defaults) -> (see in https://github.com/mscdex/ssh2-streams) to the grunt task! it was one of the following:

                algorithms: {
                    kex: [
                        'diffie-hellman-group1-sha1',
                        'diffie-hellman-group-exchange-sha1',
                        'diffie-hellman-group14-sha1',
                        'diffie-hellman-group-exchange-sha256',
                        'ecdh-sha2-nistp521',
                        'ecdh-sha2-nistp384',
                        'ecdh-sha2-nistp256'
                    ],
                    cipher: [
                        'aes128-ctr',
                        'aes192-ctr',
                        'aes256-ctr',
                        'aes128-gcm',
                        'aes128-gcm@openssh.com',
                        'aes256-gcm',
                        'aes256-gcm@openssh.com',
                        'aes256-cbc',
                        'aes192-cbc',
                        'aes128-cbc',
                        'blowfish-cbc',
                        '3des-cbc',
                        'arcfour256',
                        'arcfour128',
                        'cast128-cbc',
                        'arcfour'
                    ]
                }

so i could manage to solve the problem! awesome!
